### PR TITLE
Move contents of dir when dir already exists in the destination

### LINKED ISSUE #47: Fix moving directory with files to destination where directory with same name exists
Let's say we have:
```
/source
/source/dir
/source/dir/file1.txt
/dest
/dest/dir
/dest/dir/file2.txt
```
When we move `/source/dir` to `/dest/dir`:
An error occures.

Instead of expected:
```
/source
/dest/dir
/dest/dir/file1.txt
/dest/dir/file2.txt
```

### PR DESCRIPTION
**Pull request by ocerman**
FIX #47 + added alerts when user is trying to overwrite directory with file and vice versa

### CODE REVIEW

**Comment by humdingerb** [comment]
Sorry for the delay.
I found an issue, given a situation like this:
```
/source
/source/item1
/source/item2 
/dest
/dest/dir
/dest/item1
/dest/item2
```
The items in source are folders, the items in dest are files.
Copying the folders in source to dest, it won't complain that there are already files in dest with those names. The files are not replaced with the folders.

**Comment by ocerman** [comment]
@humdingerb the previous commit was handling only when moving files. I have pushed another commit that handles this when copying files.

**Comment by humdingerb** [comment]
Alright, that works now. :)
One more thing: when trying to copy one folder to where it would clash with a file of the same name, there's a "Skip all" button in the alert. The other way around, when you try to copy one file onto  a folder with that same name, that unneeded "Skipp all" button is supressed. Can that "Skip all" button be removed in the first case as well?

**Comment by ocerman** [comment]
@humdingerb fixed

**Comment by humdingerb** [comment]
Thank you!

**Pull request merged**
