### PR TITLE
Added "Get Info" dialog for multiple files

### LINKED ISSUE #3: Get info for multiple files
Getting info on multiple files does nothing, so either it should be disabled in this case or get the total size of the selected files/folders.

### PR DESCRIPTION
**Pull request by ocerman**
Fixes #3

### CODE REVIEW

**Comment by humdingerb** [comment]
I'm not much of a coder, so others may want to chime in here...

While it does work, it seems to me that there's quite a bit of code duplication from GenesisGetInfoWindow() to GenesisGetMultiInfoWindow().
Maybe the layouting stuff could be shared in a separate function and GenesisGetInfoWindow() overloaded with a BStringList parameter variant (or even always use a BStringList that just happen to have only one item in case of only one selected file)?

As I said, I'm not really a programmer, so I may be quite wrong...

**Comment by ocerman** [comment]
@humdingerb I have made changes to my previous commit, so now everything is under GenesisGetInfoWindow

**Comment by humdingerb** [comment]
Thanks! Looks good to me.
I'll wait a few days with the merge to give others time to chime in.

**Comment by humdingerb** [comment]
Merged!
Do you have more PRs in the near future, or should I go ahead and update the recipe to get this into HaikuDepot?

**Comment by ocerman** [comment]
@humdingerb thx,I will try to do more PRs soon.

**Comment by humdingerb** [comment]
Great! Let's wait some more and maybe go for an actually bumped version/release.

**Comment by smccrearyx** [comment]
When making changes to this i'd suggest to bump the  minor version by one for each bug you fix and when fixing the last open bug and if you are satisfied with the current state, to then bump the middle version, or if you feel it ready for prime time then jump it right to 1.0.0

Also remember to update the copyright years for files you modify and in GenesisResources.rdef

**Pull request merged**
