### PR TITLE
Added option not to follow symlink directories.

### LINKED ISSUE #5: Don't always follow symlink directories
Symlinks are often used to maintain some directory structure, so sometimes it's more logical not to follow symlinks. We can offer an option to adjust this behavior.

### PR DESCRIPTION
**Pull request by ocerman**
FIX #5

### CODE REVIEW

**Comment by humdingerb** [comment]
Can you give an example of the symlink issue solved?
If I have  "dir/folder" and "folder" is a symlink to some folder and I copy "dir" somewhere, the result is the same with the new settings active and not-active: I now have a copy of "dir" with that symlinked folder in it.
I probably miss the point...

**Comment by ocerman** [comment]
// edit: got it wrong, it is fixed now.

The point is wheter when entering the symlink the path changes to real loaction of the link, or it includes the link. Basically it is same difference like between commands `cd` and `cd -P`. Also midnight commander have this option.

For example, when we have in /boot/home:
```
films -> /another-drive/media/videos
```

Now, with follow symlink directories disabled:
We are in `/boot/home`
Enter films: `/another-drive/media/videos`
Then go up: `/another-driver/media`

With follow symlink directories enabled:
We are in `/boot/home`
Enter films: `/boot/home/films`
Then go up: `/boot/home`

**Comment by humdingerb** [comment]
Thanks. I understand now.
But I think you have reversed the logic of the checkbox in ther preferences...

Does Midnight Commander call that option the same?
Maybe we can come up with something better. "Keep symlinked directory paths when navigating"?
Or something better... your call.

**Comment by ocerman** [comment]
MC calls it similiarly "cd follows links". Yeah, that name is confusing. I will change it.

**Comment by ocerman** [comment]
@humdingerb  I have changed it to your suggested label "Keep symlinked directory paths when navigating".

**Comment by humdingerb** [comment]
Thank you!

**Pull request merged**
